version: "3.1"

assistant_id: indonesian_food_chatbot

language: id

pipeline:
  - name: WhitespaceTokenizer
  
  - name: RegexFeaturizer
  
  - name: LexicalSyntacticFeaturizer
  
  - name: CountVectorsFeaturizer
    min_ngram: 1
    max_ngram: 3
    
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 2
    max_ngram: 4
    
  - name: DIETClassifier
    epochs: 80
    constrain_similarities: true
    model_confidence: softmax
    entity_recognition: true
    intent_classification: true
    
  - name: EntitySynonymMapper
  
  - name: ResponseSelector
    epochs: 60
    constrain_similarities: true
    model_confidence: softmax
    
  - name: FallbackClassifier
    threshold: 0.4
    ambiguity_threshold: 0.15

policies:
  - name: MemoizationPolicy
    max_history: 3
    
  - name: RulePolicy
    core_fallback_threshold: 0.3
    core_fallback_action_name: "utter_default"
    enable_fallback_prediction: true
    
  - name: UnexpecTEDIntentPolicy
    max_history: 4
    epochs: 80
    
  - name: TEDPolicy
    max_history: 4
    epochs: 80
    constrain_similarities: true